[API]
PUBLIC_KEY = ""
SECRET_KEY = ""

[POSITION]
SYMBOL = "ETHUSDT"
COIN_PRECISION = 2
TP_RATIO = 0.0050
SL_RATIO = 0.0050
LEVERAGE = 1

[RUNTIME]
TEST_MODE = true
DEBUG_MODE = false
INTERVAL = "15m"
SLEEP_DURATION = 30.0